#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me
# is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
new_configuration="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$new_configuration/" /etc/nginx/sites-enabled/default
sudo service nginx restart
