#!/usr/bin/env bash
# Install and configure HAproxy on your loadbalancer-01 server
# and Configure HAproxy so that it send traffic to web-01 and web-02

sudo apt-get -y update
apt-get -y install haproxy

apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 17272-web-01 44.200.83.158:80 check
   server 17272-web-02 3.237.16.226:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
