#!/usr/bin/env bash
# Install and configure HAproxy on your loadbalancer-01 server
# and Configure HAproxy so that it send traffic to web-01 and web-02

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

lb_config=\
"
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 154322-web-01 34.227.93.37:80 check
    server 154322-web-02 54.162.78.64:80 check
"

echo "$lb_config" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
