#!/usr/bin/env bash
# Debugging Ubuntu container’s Nginx installation
# from listening on port 80

cd /etc/nginx/sites-enabled/ || exit;
rm default;
ln -s /etc/nginx/sites-available/default default;
service nginx restart
