#!/usr/bin/env bash
# Displays "To infinity and beyond"
# with a sleep 2 in between each iteration
# and "I am invincible!!!" when recieving a SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"'
done
