#!/usr/bin/env bash
# Gives infomation about school file

file="school"
if test ! -f "$file"; then
	echo "school file does not exist"
else
	echo "school file exists"
	if [ -s "$file" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	echo "school is a regular file"
fi
