#!/usr/bin/env bash
# Configure SSH configuration file for the local SSH client
# so that you can connect to a server without typing a password

Host *
    Hostname 107.22.142.218
	User ubuntu
	IdentifyFile ~/.ssh.school
	PasswordAuthentication no
